### ISSUE TITLE
Bug in DataTableWithSearch - Search Does Not Work, Throws Error

### ISSUE THREAD

**Issue by zischwartz** [lorenries/teddy#7]
In the [storybook](https://data.newamerica.org/component-library/?selectedKind=Data%20Table&selectedStory=Data%20Table&full=0&addons=0&stories=1&panelRight=0), as well as in what I'm working on, when you start typing in the search input, it throws an error:
```
TypeError: Cannot read property 'value' of undefined
```

Looks like the problem is [here](https://github.com/lorenries/teddy/blob/master/packages/data-table/src/DataTableWithSearch/withSearch.js#L12-L13) where it's expecting an event, but it's receiving the search string instead from [this line in the search component](https://github.com/lorenries/teddy/blob/master/packages/components/src/Search/index.js#L15)

**Comment by lorenries** [comment]
Good catch, thanks. I'll push a fix today.

For all of the UI components, I was sending the event's `target.value` to the `onChange` handlers, but realized it'd probably be more useful for parent component to receive the entire event. Looks like my update didn't catch everything.

**Comment by zischwartz** [comment]
👍 👍

**Comment by lorenries** [comment]
Fixed by 6638ae0302451b9b478e07abf6c8f9035248725d

Decided not to send the entire event to the parent's handler, because I don't want to mess around with persisting React's synthetic events.

If you bump to `@newamerica/data-table@0.0.6` everything should be working properly.
